name: see all github action with json(github)
on: workflow_dispatch

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: infos de mon context github
        run: echo "${{ toJson(github) }}"
